# Generated by Django 3.2.3 on 2021-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_createevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createevent',
        ),
        migrations.AddField(
            model_name='event',
            name='a_user',
            field=models.IntegerField(null=True),
        ),
    ]
