# Generated by Django 3.2.3 on 2021-05-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20210518_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
