# Generated by Django 3.2.3 on 2021-05-20 06:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0005_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='usercreated',
        ),
    ]
