# Generated by Django 3.2.3 on 2021-05-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_createevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='createevent',
        ),
    ]
